# Site settings
title: Common Lisp
domain: "lisp-lang.org"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: none

sass:
  implementation: sass-embedded
  style: compressed
  load_paths:
    - _sass

defaults:
  - scope:
      path: "learn"
    values:
      layout: "learn"
      permalink: "/learn/:title"
      css_file: "learn"
  - scope:
      path: "success"
    values:
      layout: "success"
      css_file: success
  - scope:
      path: "learn/_posts/tutorials"
    values:
      kind: "tutorial"
  - scope:
      path: "learn/_posts/guides"
    values:
      kind: "guide"
  - scope:
      path: "news"
    values:
      permalink: /news/:year/:month/:day/:title/
      layout: "news"
      css_file: "news"
  - scope:
      path: "wiki"
    values:
      permalink: /wiki/article/:title
      layout: "wiki"
      css_file: "wiki"
  - scope:
      path: "wiki/_posts"
    values:
      layout: "wiki-article"
